apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-api
  name: hello-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - image: celagus/hello-api
        name: hello-api
        securityContext:
          allowPrivilegeEscalation: false