apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-api
  name: hello-api
  namespace: hello-api
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-api
  type: NodePort