name: Hello-world API Pipeline
on: [push]
jobs:
  job1:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit tests
        run: |
          pytest hello_world/test/*
  job2:
    name: SAST Scan
    needs: job1
    env:
      DDOJO_URL: http://bc0217973647.ngrok.io
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: Check celagus DDojo scripts
        uses: actions/checkout@v2
        with:
          repository: celagus/defect-dojo
          path: defect-dojo
      - name: Install Bandit
        run: |
          python3 -m pip install --upgrade pip
          pip3 install bandit
      - name: Run Bandit
        run: |
          /home/runner/.local/bin/bandit -x hello_world/test/u_test.py -r . -o bandit.out -f json || true
      - name: Upload Bandit output to DefectDojo
        run: |
          python3 defect-dojo/import_scan.py -b $DDOJO_URL -k ${{secrets.DDOJO_TOKEN}} -f bandit.out -e 1 -t 'Bandit Scan'
  job3:
    name: IaC Scan
    needs: job1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@v1
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          iac_dir: terraform/aws